version: '3'
services:
  astt-cam-software-gui:
    image: astt-cam-software:latest
    container_name: astt-cam-software-gui
    ports:
      - 5000:5000
    network_mode: "host"
    environment:
      - PYTHONPATH=/app/src
    command: >
        bash -c "python3 src/astt_gui/app.py"

  astt-antenna-simulator:
    image: astt-cam-software:latest
    container_name: astt-antenna-simulator
    network_mode: "host"
    command: >
        bash -c "cd src/antenna_simulator
        && ./slave"